.TH "audio" 3 "Version .." "SFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
audio \- Audio module
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsf::AlResource\fP"
.br
.RI "Base class for classes that require an OpenAL context\&. "
.ti -1c
.RI "class \fBsf::InputSoundFile\fP"
.br
.RI "Provide read access to sound files\&. "
.ti -1c
.RI "class \fBsf::Listener\fP"
.br
.RI "The audio listener is the point in the scene from where all the sounds are heard\&. "
.ti -1c
.RI "class \fBsf::Music\fP"
.br
.RI "Streamed music played from an audio file\&. "
.ti -1c
.RI "class \fBsf::OutputSoundFile\fP"
.br
.RI "Provide write access to sound files\&. "
.ti -1c
.RI "class \fBsf::Sound\fP"
.br
.RI "Regular sound that can be played in the audio environment\&. "
.ti -1c
.RI "class \fBsf::SoundBuffer\fP"
.br
.RI "Storage for audio samples defining a sound\&. "
.ti -1c
.RI "class \fBsf::SoundBufferRecorder\fP"
.br
.RI "Specialized \fBSoundRecorder\fP which stores the captured audio data into a sound buffer\&. "
.ti -1c
.RI "class \fBsf::SoundFileFactory\fP"
.br
.RI "Manages and instantiates sound file readers and writers\&. "
.ti -1c
.RI "class \fBsf::SoundFileReader\fP"
.br
.RI "Abstract base class for sound file decoding\&. "
.ti -1c
.RI "class \fBsf::SoundFileWriter\fP"
.br
.RI "Abstract base class for sound file encoding\&. "
.ti -1c
.RI "class \fBsf::SoundRecorder\fP"
.br
.RI "Abstract base class for capturing sound data\&. "
.ti -1c
.RI "class \fBsf::SoundSource\fP"
.br
.RI "Base class defining a sound's properties\&. "
.ti -1c
.RI "class \fBsf::SoundStream\fP"
.br
.RI "Abstract base class for streamed audio sources\&. "
.in -1c
.SH "Detailed Description"
.PP 


Sounds, streaming (musics or custom sources), recording, spatialization\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SFML from the source code\&.
