.TH "sf::Event::MouseButtonEvent" 3 "Version .." "SFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sf::Event::MouseButtonEvent \- \fBMouse\fP buttons events parameters (MouseButtonPressed, MouseButtonReleased)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SFML/Window/Event\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMouse::Button\fP \fBbutton\fP"
.br
.RI "Code of the button that has been pressed\&. "
.ti -1c
.RI "int \fBx\fP"
.br
.RI "X position of the mouse pointer, relative to the left of the owner window\&. "
.ti -1c
.RI "int \fBy\fP"
.br
.RI "Y position of the mouse pointer, relative to the top of the owner window\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBMouse\fP buttons events parameters (MouseButtonPressed, MouseButtonReleased) 
.PP
Definition at line \fB96\fP of file \fBEvent\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMouse::Button\fP sf::Event::MouseButtonEvent::button"

.PP
Code of the button that has been pressed\&. 
.PP
Definition at line \fB98\fP of file \fBEvent\&.hpp\fP\&.
.SS "int sf::Event::MouseButtonEvent::x"

.PP
X position of the mouse pointer, relative to the left of the owner window\&. 
.PP
Definition at line \fB99\fP of file \fBEvent\&.hpp\fP\&.
.SS "int sf::Event::MouseButtonEvent::y"

.PP
Y position of the mouse pointer, relative to the top of the owner window\&. 
.PP
Definition at line \fB100\fP of file \fBEvent\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SFML from the source code\&.
