.TH "sf::Ftp" 3 "Version .." "SFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sf::Ftp \- A FTP client\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SFML/Network/Ftp\&.hpp>\fP
.PP
Inherits \fBsf::NonCopyable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectoryResponse\fP"
.br
.RI "Specialization of FTP response returning a directory\&. "
.ti -1c
.RI "class \fBListingResponse\fP"
.br
.RI "Specialization of FTP response returning a filename listing\&. "
.ti -1c
.RI "class \fBResponse\fP"
.br
.RI "Define a FTP response\&. "
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTransferMode\fP { \fBBinary\fP, \fBAscii\fP, \fBEbcdic\fP }"
.br
.RI "Enumeration of transfer modes\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Ftp\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "\fBResponse\fP \fBconnect\fP (const \fBIpAddress\fP &server, unsigned short port=21, \fBTime\fP timeout=\fBTime::Zero\fP)"
.br
.RI "Connect to the specified FTP server\&. "
.ti -1c
.RI "\fBResponse\fP \fBdisconnect\fP ()"
.br
.RI "Close the connection with the server\&. "
.ti -1c
.RI "\fBResponse\fP \fBlogin\fP ()"
.br
.RI "Log in using an anonymous account\&. "
.ti -1c
.RI "\fBResponse\fP \fBlogin\fP (const std::string &name, const std::string &password)"
.br
.RI "Log in using a username and a password\&. "
.ti -1c
.RI "\fBResponse\fP \fBkeepAlive\fP ()"
.br
.RI "Send a null command to keep the connection alive\&. "
.ti -1c
.RI "\fBDirectoryResponse\fP \fBgetWorkingDirectory\fP ()"
.br
.RI "Get the current working directory\&. "
.ti -1c
.RI "\fBListingResponse\fP \fBgetDirectoryListing\fP (const std::string &directory='')"
.br
.RI "Get the contents of the given directory\&. "
.ti -1c
.RI "\fBResponse\fP \fBchangeDirectory\fP (const std::string &directory)"
.br
.RI "Change the current working directory\&. "
.ti -1c
.RI "\fBResponse\fP \fBparentDirectory\fP ()"
.br
.RI "Go to the parent directory of the current one\&. "
.ti -1c
.RI "\fBResponse\fP \fBcreateDirectory\fP (const std::string &name)"
.br
.RI "Create a new directory\&. "
.ti -1c
.RI "\fBResponse\fP \fBdeleteDirectory\fP (const std::string &name)"
.br
.RI "Remove an existing directory\&. "
.ti -1c
.RI "\fBResponse\fP \fBrenameFile\fP (const std::string &file, const std::string &newName)"
.br
.RI "Rename an existing file\&. "
.ti -1c
.RI "\fBResponse\fP \fBdeleteFile\fP (const std::string &name)"
.br
.RI "Remove an existing file\&. "
.ti -1c
.RI "\fBResponse\fP \fBdownload\fP (const std::string &remoteFile, const std::string &localPath, \fBTransferMode\fP mode=\fBBinary\fP)"
.br
.RI "Download a file from the server\&. "
.ti -1c
.RI "\fBResponse\fP \fBupload\fP (const std::string &localFile, const std::string &remotePath, \fBTransferMode\fP mode=\fBBinary\fP, bool append=false)"
.br
.RI "Upload a file to the server\&. "
.ti -1c
.RI "\fBResponse\fP \fBsendCommand\fP (const std::string &command, const std::string &parameter='')"
.br
.RI "Send a command to the FTP server\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBDataChannel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A FTP client\&. 

\fBsf::Ftp\fP is a very simple FTP client that allows you to communicate with a FTP server\&.
.PP
The FTP protocol allows you to manipulate a remote file system (list files, upload, download, create, remove, \&.\&.\&.)\&.
.PP
Using the FTP client consists of 4 parts: 
.PD 0
.IP "\(bu" 1
Connecting to the FTP server 
.IP "\(bu" 1
Logging in (either as a registered user or anonymously) 
.IP "\(bu" 1
Sending commands to the server 
.IP "\(bu" 1
Disconnecting (this part can be done implicitly by the destructor)
.PP
Every command returns a FTP response, which contains the status code as well as a message from the server\&. Some commands such as \fBgetWorkingDirectory()\fP and \fBgetDirectoryListing()\fP return additional data, and use a class derived from \fBsf::Ftp::Response\fP to provide this data\&. The most often used commands are directly provided as member functions, but it is also possible to use specific commands with the \fBsendCommand()\fP function\&.
.PP
Note that response statuses >= 1000 are not part of the FTP standard, they are generated by SFML when an internal error occurs\&.
.PP
All commands, especially upload and download, may take some time to complete\&. This is important to know if you don't want to block your application while the server is completing the task\&.
.PP
Usage example: 
.PP
.nf
// Create a new FTP client
sf::Ftp ftp;

// Connect to the server
sf::Ftp::Response response = ftp\&.connect("ftp://ftp\&.myserver\&.com");
if (response\&.isOk())
    std::cout << "Connected" << std::endl;

// Log in
response = ftp\&.login("laurent", "dF6Zm89D");
if (response\&.isOk())
    std::cout << "Logged in" << std::endl;

// Print the working directory
sf::Ftp::DirectoryResponse directory = ftp\&.getWorkingDirectory();
if (directory\&.isOk())
    std::cout << "Working directory: " << directory\&.getDirectory() << std::endl;

// Create a new directory
response = ftp\&.createDirectory("files");
if (response\&.isOk())
    std::cout << "Created new directory" << std::endl;

// Upload a file to this new directory
response = ftp\&.upload("local\-path/file\&.txt", "files", sf::Ftp::Ascii);
if (response\&.isOk())
    std::cout << "File uploaded" << std::endl;

// Send specific commands (here: FEAT to list supported FTP features)
response = ftp\&.sendCommand("FEAT");
if (response\&.isOk())
    std::cout << "Feature list:\\n" << response\&.getMessage() << std::endl;

// Disconnect from the server (optional)
ftp\&.disconnect();

.fi
.PP
 
.PP
Definition at line \fB47\fP of file \fBFtp\&.hpp\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBsf::Ftp::TransferMode\fP"

.PP
Enumeration of transfer modes\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBinary \fP\fP
Binary mode (file is transfered as a sequence of bytes) 
.TP
\fB\fIAscii \fP\fP
\fBText\fP mode using ASCII encoding\&. 
.TP
\fB\fIEbcdic \fP\fP
\fBText\fP mode using EBCDIC encoding\&. 
.PP
Definition at line \fB55\fP of file \fBFtp\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sf::Ftp::~Ftp ()"

.PP
Destructor\&. Automatically closes the connection with the server if it is still opened\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBResponse\fP sf::Ftp::changeDirectory (const std::string & directory)"

.PP
Change the current working directory\&. The new directory must be relative to the current one\&.
.PP
\fBParameters\fP
.RS 4
\fIdirectory\fP New working directory
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBgetWorkingDirectory\fP, \fBgetDirectoryListing\fP, \fBparentDirectory\fP 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::connect (const \fBIpAddress\fP & server, unsigned short port = \fR21\fP, \fBTime\fP timeout = \fR\fBTime::Zero\fP\fP)"

.PP
Connect to the specified FTP server\&. The port has a default value of 21, which is the standard port used by the FTP protocol\&. You shouldn't use a different value, unless you really know what you do\&. This function tries to connect to the server so it may take a while to complete, especially if the server is not reachable\&. To avoid blocking your application for too long, you can use a timeout\&. The default value, \fBTime::Zero\fP, means that the system timeout will be used (which is usually pretty long)\&.
.PP
\fBParameters\fP
.RS 4
\fIserver\fP Name or address of the FTP server to connect to 
.br
\fIport\fP Port used for the connection 
.br
\fItimeout\fP Maximum time to wait
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBdisconnect\fP 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::createDirectory (const std::string & name)"

.PP
Create a new directory\&. The new directory is created as a child of the current working directory\&.
.PP
\fBParameters\fP
.RS 4
\fIname\fP Name of the directory to create
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBdeleteDirectory\fP 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::deleteDirectory (const std::string & name)"

.PP
Remove an existing directory\&. The directory to remove must be relative to the current working directory\&. Use this function with caution, the directory will be removed permanently!
.PP
\fBParameters\fP
.RS 4
\fIname\fP Name of the directory to remove
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBcreateDirectory\fP 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::deleteFile (const std::string & name)"

.PP
Remove an existing file\&. The file name must be relative to the current working directory\&. Use this function with caution, the file will be removed permanently!
.PP
\fBParameters\fP
.RS 4
\fIname\fP File to remove
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBrenameFile\fP 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::disconnect ()"

.PP
Close the connection with the server\&. 
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBconnect\fP 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::download (const std::string & remoteFile, const std::string & localPath, \fBTransferMode\fP mode = \fR\fBBinary\fP\fP)"

.PP
Download a file from the server\&. The filename of the distant file is relative to the current working directory of the server, and the local destination path is relative to the current directory of your application\&. If a file with the same filename as the distant file already exists in the local destination path, it will be overwritten\&.
.PP
\fBParameters\fP
.RS 4
\fIremoteFile\fP Filename of the distant file to download 
.br
\fIlocalPath\fP The directory in which to put the file on the local computer 
.br
\fImode\fP Transfer mode
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBupload\fP 
.RE
.PP

.SS "\fBListingResponse\fP sf::Ftp::getDirectoryListing (const std::string & directory = \fR''\fP)"

.PP
Get the contents of the given directory\&. This function retrieves the sub-directories and files contained in the given directory\&. It is not recursive\&. The \fIdirectory\fP parameter is relative to the current working directory\&.
.PP
\fBParameters\fP
.RS 4
\fIdirectory\fP Directory to list
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBgetWorkingDirectory\fP, \fBchangeDirectory\fP, \fBparentDirectory\fP 
.RE
.PP

.SS "\fBDirectoryResponse\fP sf::Ftp::getWorkingDirectory ()"

.PP
Get the current working directory\&. The working directory is the root path for subsequent operations involving directories and/or filenames\&.
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBgetDirectoryListing\fP, \fBchangeDirectory\fP, \fBparentDirectory\fP 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::keepAlive ()"

.PP
Send a null command to keep the connection alive\&. This command is useful because the server may close the connection automatically if no command is sent\&.
.PP
\fBReturns\fP
.RS 4
Server response to the request 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::login ()"

.PP
Log in using an anonymous account\&. Logging in is mandatory after connecting to the server\&. Users that are not logged in cannot perform any operation\&.
.PP
\fBReturns\fP
.RS 4
Server response to the request 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::login (const std::string & name, const std::string & password)"

.PP
Log in using a username and a password\&. Logging in is mandatory after connecting to the server\&. Users that are not logged in cannot perform any operation\&.
.PP
\fBParameters\fP
.RS 4
\fIname\fP User name 
.br
\fIpassword\fP Password
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::parentDirectory ()"

.PP
Go to the parent directory of the current one\&. 
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBgetWorkingDirectory\fP, \fBgetDirectoryListing\fP, \fBchangeDirectory\fP 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::renameFile (const std::string & file, const std::string & newName)"

.PP
Rename an existing file\&. The filenames must be relative to the current working directory\&.
.PP
\fBParameters\fP
.RS 4
\fIfile\fP File to rename 
.br
\fInewName\fP New name of the file
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBdeleteFile\fP 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::sendCommand (const std::string & command, const std::string & parameter = \fR''\fP)"

.PP
Send a command to the FTP server\&. While the most often used commands are provided as member functions in the \fBsf::Ftp\fP class, this method can be used to send any FTP command to the server\&. If the command requires one or more parameters, they can be specified in \fIparameter\fP\&. If the server returns information, you can extract it from the response using \fBResponse::getMessage()\fP\&.
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Command to send 
.br
\fIparameter\fP Command parameter
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request 
.RE
.PP

.SS "\fBResponse\fP sf::Ftp::upload (const std::string & localFile, const std::string & remotePath, \fBTransferMode\fP mode = \fR\fBBinary\fP\fP, bool append = \fRfalse\fP)"

.PP
Upload a file to the server\&. The name of the local file is relative to the current working directory of your application, and the remote path is relative to the current directory of the FTP server\&.
.PP
The append parameter controls whether the remote file is appended to or overwritten if it already exists\&.
.PP
\fBParameters\fP
.RS 4
\fIlocalFile\fP Path of the local file to upload 
.br
\fIremotePath\fP The directory in which to put the file on the server 
.br
\fImode\fP Transfer mode 
.br
\fIappend\fP Pass true to append to or false to overwrite the remote file if it already exists
.RE
.PP
\fBReturns\fP
.RS 4
Server response to the request
.RE
.PP
\fBSee also\fP
.RS 4
\fBdownload\fP 
.RE
.PP

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class DataChannel\fR [friend]\fP"

.PP
Definition at line \fB531\fP of file \fBFtp\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SFML from the source code\&.
