.TH "sf::Music::Span< T >" 3 "Version .." "SFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sf::Music::Span< T > \- Structure defining a time range using the template type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SFML/Audio/Music\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpan\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBSpan\fP (T off, T len)"
.br
.RI "Initialization constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBoffset\fP"
.br
.RI "The beginning offset of the time range\&. "
.ti -1c
.RI "T \fBlength\fP"
.br
.RI "The length of the time range\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct sf::Music::Span< T >"Structure defining a time range using the template type\&. 
.PP
Definition at line \fB57\fP of file \fBMusic\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBsf::Music::Span\fP< T >::Span ()\fR [inline]\fP"

.PP
Default constructor\&. 
.PP
Definition at line \fB63\fP of file \fBMusic\&.hpp\fP\&.
.SS "template<typename T > \fBsf::Music::Span\fP< T >::Span (T off, T len)\fR [inline]\fP"

.PP
Initialization constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIoff\fP Initial Offset 
.br
\fIlen\fP Initial Length 
.RE
.PP

.PP
Definition at line \fB75\fP of file \fBMusic\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > T \fBsf::Music::Span\fP< T >::length"

.PP
The length of the time range\&. 
.PP
Definition at line \fB83\fP of file \fBMusic\&.hpp\fP\&.
.SS "template<typename T > T \fBsf::Music::Span\fP< T >::offset"

.PP
The beginning offset of the time range\&. 
.PP
Definition at line \fB82\fP of file \fBMusic\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SFML from the source code\&.
