.TH "sf::SoundStream::Chunk" 3 "Version .." "SFML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sf::SoundStream::Chunk \- Structure defining a chunk of audio data to stream\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SFML/Audio/SoundStream\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const Int16 * \fBsamples\fP"
.br
.RI "Pointer to the audio samples\&. "
.ti -1c
.RI "std::size_t \fBsampleCount\fP"
.br
.RI "Number of samples pointed by Samples\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure defining a chunk of audio data to stream\&. 
.PP
Definition at line \fB53\fP of file \fBSoundStream\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::size_t sf::SoundStream::Chunk::sampleCount"

.PP
Number of samples pointed by Samples\&. 
.PP
Definition at line \fB56\fP of file \fBSoundStream\&.hpp\fP\&.
.SS "const Int16* sf::SoundStream::Chunk::samples"

.PP
Pointer to the audio samples\&. 
.PP
Definition at line \fB55\fP of file \fBSoundStream\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SFML from the source code\&.
